# -*- coding: utf-8 -*-
# Pages de services FR (≈ 1 000 mots chacune). Importées par content_fr.py.

SERVICE_PAGES = [
# ───────────────────────────── LOGEMENT
{
    "key": "housing", "slug": "logement", "alt": "housing", "nav": "Logement", "priority": "high", "image": "banner-logement.jpg",
    "title": "Logement pour collaborateurs en mission à Paris | Eden Corporate Mobility",
    "desc": "Appartements meublés, aparthotels et hôtels pour vos salariés en déplacement à Paris et en Île-de-France. De quelques nuits à plusieurs mois, près du lieu de mission.",
    "h1": "Un logement prêt à vivre pour chaque collaborateur, à Paris et en Île-de-France",
    "lead": "Vous nous dites qui vient, quand, où il travaille et avec quel budget. Nous sélectionnons, réservons et suivons le logement pendant toute la mission. Votre collaborateur arrive, les clés l'attendent.",
    "sections": [
        {"type": "prose", "heading": "Le logement décide de la réussite d'une mission", "html": "<p>Un collaborateur envoyé à Paris passe plus de temps dans son logement que dans n'importe quel autre lieu de sa mission. S'il dort mal, s'il met une heure pour rejoindre le site, s'il n'a pas de quoi cuisiner ni de table pour travailler, sa mission en souffre, et son envie de repartir aussi. À l'inverse, un appartement calme, bien situé et vraiment équipé fait de la mission une expérience positive dont il parlera à ses collègues.</p><p>C'est pour cela que nous ne transmettons pas des listes d'annonces. Nous sélectionnons des logements que nous connaissons, adaptés à la durée du séjour, au lieu de mission et au profil de la personne : un consultant seul pendant six mois, une équipe de huit ouvriers pendant trois semaines, une famille qui s'installe pour deux ans. Chaque cas appelle un format différent, et nous vous proposons celui qui tient le budget.</p>"},
        {"type": "features", "heading": "Trois formats, selon la durée et le rythme de la mission", "intro": "Nous travaillons avec les trois familles de logements professionnels. Le choix dépend de la durée, du lieu de mission, du nombre de personnes et de votre budget.", "items": [
            {"img": "format-appartement.jpg", "title": "Appartement meublé", "text": "Pour les séjours d'un mois et plus. Un vrai chez-soi avec cuisine équipée, espace de travail, lave-linge et calme. C'est le format des consultants, des cadres en mutation et des expatriés. Le contrat est établi au nom de votre entreprise, avec une durée adaptée à la mission."},
            {"img": "format-aparthotel.jpg", "title": "Aparthotel", "text": "Pour les séjours de quelques semaines. Le confort d'un appartement avec les services d'un hôtel : ménage régulier, réception, linge fourni, arrivée possible en soirée. Pratique pour les rotations d'équipe et les missions dont la date de fin bouge."},
            {"img": "format-hotel.jpg", "title": "Hôtel", "text": "Pour les séjours courts et les arrivées en urgence. Nous réservons auprès d'établissements que nous connaissons, proches de votre lieu de mission, à des conditions négociées pour les séjours répétés. Petit-déjeuner et annulation souple selon les cas."},
        ]},
        {"type": "media", "items": [
            {"img": "logement-quartier.jpg", "heading": "Où loger vos collaborateurs en Île-de-France", "html": "<p>Le bon quartier n'est pas le plus beau : c'est celui d'où l'on rejoint le lieu de mission sans y penser. Nous raisonnons à partir de l'adresse de travail et des horaires réels de votre collaborateur.</p><ul><li><strong>Paris intra-muros</strong> pour les missions dans les quartiers d'affaires du centre et de l'ouest, avec une préférence pour les arrondissements bien desservis par le métro.</li><li><strong>La Défense, Neuilly, Boulogne, Issy</strong> pour les sièges de groupes et les cabinets de conseil.</li><li><strong>Saint-Denis, Plaine Commune, Roissy</strong> pour les chantiers, la logistique et les missions aéroportuaires.</li><li><strong>Marne-la-Vallée, Créteil, Massy et le plateau de Saclay</strong> pour les projets industriels, techniques et de recherche.</li></ul><p>Pour une équipe, nous privilégions un même immeuble ou un même secteur, afin que tout le monde ait le même temps de trajet et puisse se retrouver le soir.</p>"},
            {"img": "logement-groupe.jpg", "heading": "Pour les groupes et les équipes", "html": "<p>Plusieurs personnes sur un même projet ou un même chantier ? Nous logeons les équipes ensemble, dans des appartements partagés avec chambres individuelles, dans une résidence ou dans un hôtel selon le budget et les règles d'hébergement de votre secteur.</p><p>Nous gérons les arrivées échelonnées, les remplacements en cours de mission et les prolongations. Vous avez une seule liste, tenue à jour, de qui est logé où et jusqu'à quand. Plus vous nous prévenez tôt, plus nous avons de choix ; mais nous savons aussi absorber une arrivée décidée la veille.</p>"},
        ]},
        {"type": "twocol", "heading": "Ce que nous vérifions avant de vous proposer un logement", "aside": "<p class=\"muted\">Un logement n'est pas un listing. Nous le choisissons comme si c'était pour un membre de notre équipe.</p>",
         "html": """<dl class="reasons">
<dt>La localisation</dt><dd>Le temps de trajet réel vers le lieu de mission, en transports en commun ou en voiture, aux heures où votre collaborateur se déplace. Et la proximité des commerces pour la vie quotidienne.</dd>
<dt>Le calme et le confort</dt><dd>Literie, isolation, lumière, espace pour travailler. Ce qui fait la différence entre un séjour subi et un séjour agréable.</dd>
<dt>L'équipement</dt><dd>Cuisine complète, lave-linge, wifi fiable, télévision, linge de maison. Tout ce qu'il faut pour vivre, pas seulement pour dormir.</dd>
<dt>Les conditions</dt><dd>Durée, flexibilité, ménage inclus ou non, dépôt de garantie, état des lieux : tout est écrit noir sur blanc avant la réservation.</dd>
<dt>Le propriétaire ou l'exploitant</dt><dd>Nous travaillons avec des interlocuteurs réactifs, capables d'intervenir vite si une chaudière tombe en panne un dimanche.</dd>
</dl>"""},
        {"type": "steps", "heading": "Comment se déroule une réservation", "items": [
            {"title": "Vous nous appelez ou remplissez le formulaire", "text": "Dates, nombre de personnes, adresse de mission, budget, besoins particuliers. Dix minutes suffisent, en français ou en anglais."},
            {"title": "Nous vous proposons une sélection", "text": "Deux ou trois logements adaptés, avec photos, localisation, temps de trajet et conditions, dans un devis unique. Vous choisissez."},
            {"title": "Nous réservons et préparons l'arrivée", "text": "Contrat au nom de votre entreprise, remise des clés organisée, transfert depuis l'aéroport si vous le souhaitez, logement vérifié avant l'arrivée."},
            {"title": "Nous suivons le séjour", "text": "Un numéro à appeler pour votre collaborateur et pour vous. Prolongation, changement de logement, problème technique : nous gérons."},
        ]},
        {"type": "prose", "heading": "Ce qui est compris", "html": "<p>Selon le format retenu, le devis précise ce qui est inclus : loyer ou nuitées, charges, linge, ménage d'entrée et de sortie, ménage régulier pour les aparthotels et les hôtels, wifi, taxe de séjour le cas échéant. Nous indiquons aussi ce qui reste à la charge de l'occupant, comme les consommations supplémentaires ou les dégradations. Il n'y a pas de frais cachés : si un élément n'est pas dans le devis, il n'est pas facturé.</p><p>Pour les séjours longs, nous pouvons ajouter les <a href=\"/services-bien-etre/\">services bien-être</a> (accueil, conciergerie, sport, accompagnement des familles) et organiser les <a href=\"/transports/\">transports</a>, coordonnés avec le logement et facturés sur le même document.</p>"},
        {"type": "faq", "heading": "Questions sur le logement", "items": [
            {"q": "Qui signe : l'entreprise ou le collaborateur ?", "a": "<p>Dans la plupart des cas, la réservation est établie au nom de votre entreprise, qui reste notre interlocuteur contractuel et le destinataire des factures. Votre collaborateur n'a rien à avancer et rien à signer sur place, sauf l'état des lieux.</p>"},
            {"q": "Quelle est la durée minimale ?", "a": "<p>Il n'y en a pas vraiment : nous logeons pour quelques nuits à l'hôtel comme pour plusieurs années en appartement. En dessous d'un mois, l'hôtel ou l'aparthotel sont généralement plus adaptés qu'un appartement meublé.</p>"},
            {"q": "Que se passe-t-il si la mission s'allonge ou se termine plus tôt ?", "a": "<p>Vous nous prévenez, nous prolongeons le séjour ou organisons une solution de relais. En cas de fin anticipée, les conditions de préavis indiquées au devis s'appliquent ; nous les négocions le plus souples possible dès le départ.</p>"},
            {"q": "Pouvez-vous loger une famille ?", "a": "<p>Oui. Pour une expatriation ou une mutation, nous cherchons un logement adapté à la famille : nombre de chambres, quartier, proximité des écoles et des crèches, et nous accompagnons l'installation.</p>"},
            {"q": "Les logements sont-ils visités ?", "a": "<p>Nous sélectionnons des logements que nous connaissons et nous vérifions l'état de chacun avant l'arrivée de votre collaborateur. Si quelque chose ne correspond pas à ce qui a été convenu, nous le réglons avant qu'il ne pose ses valises.</p>"},
        ]},
    ],
},
# ───────────────────────────── TRANSPORTS
{
    "key": "transport", "slug": "transports", "alt": "transport", "nav": "Transports", "priority": "high", "image": "banner-transports.jpg",
    "title": "Transports pour collaborateurs en déplacement à Paris | Eden Corporate Mobility",
    "desc": "Transferts aéroport et gare, trajets quotidiens et déplacements d'équipes à Paris et en Île-de-France, coordonnés avec le logement de vos collaborateurs.",
    "h1": "Des collaborateurs qui arrivent à l'heure, sans chercher leur chemin",
    "lead": "De l'aéroport au logement, du logement au lieu de mission, et pour tous les déplacements d'équipe entre les deux : nous organisons les trajets de vos collaborateurs en Île-de-France et nous les coordonnons avec leur hébergement.",
    "sections": [
        {"type": "prose", "heading": "Pourquoi le transport fait partie du logement", "html": "<p>Un collaborateur qui débarque à Roissy à 22 h avec deux valises, sans savoir où est son logement ni comment y aller, commence sa mission fatigué et agacé. Un ouvrier qui doit prendre deux bus et un RER pour rejoindre un chantier mal desservi arrive en retard, ou pas du tout. Le transport n'est pas un détail logistique : c'est ce qui rend un logement utilisable.</p><p>C'est pourquoi nous ne séparons jamais les deux sujets. Nous choisissons d'abord le logement en fonction des déplacements de votre collaborateur, puis nous organisons les trajets qui restent. Le tout est réuni dans le même devis et suivi par la même personne.</p>"},
        {"type": "features", "heading": "Ce que nous organisons", "items": [
            {"img": "transport-aeroport.jpg", "title": "Transferts aéroport et gare", "text": "Un chauffeur attend votre collaborateur à Roissy-Charles-de-Gaulle, à Orly, à Beauvais ou en gare (Nord, Lyon, Montparnasse, Est) avec son nom sur une pancarte, et l'accompagne jusqu'à son logement. Pas de file d'attente aux taxis, pas d'application à installer, pas de surprise sur le prix."},
            {"img": "transport-quotidien.jpg", "title": "Trajets quotidiens", "text": "Passe Navigo ou titres de transport remis à l'arrivée, courses récurrentes avec chauffeur pour les horaires décalés, navette pour les équipes qui vont sur le même site. Nous adaptons la solution aux horaires réels de la mission."},
            {"img": "transport-equipe.jpg", "title": "Déplacements d'équipe", "text": "Visites de chantier, séminaires, rendez-vous clients, journée d'intégration : un véhicule et un chauffeur pour toute l'équipe, réservés à la demande et facturés sur le devis de la mission."},
        ]},
        {"type": "media", "items": [
            {"img": "transport-coordination.jpg", "heading": "Comment nous coordonnons logement et trajets", "html": "<p>Avant de proposer un logement, nous calculons le temps de trajet réel vers le lieu de mission, aux heures où votre collaborateur se déplace : un appartement à quinze minutes du site vaut mieux qu'un appartement plus beau à une heure de transport.</p><p>Ensuite, nous regardons ce qui manque. Un site industriel mal desservi par les transports en commun ? Une navette ou un véhicule. Des horaires de nuit ? Des courses avec chauffeur. Une équipe répartie sur deux chantiers ? Un point de rendez-vous commun. Chaque solution est écrite dans le devis, avec son coût, pour que vous puissiez arbitrer.</p>"},
            {"img": "service-transports.jpg", "heading": "Le premier trajet, celui qui compte", "html": "<p>Le transfert d'arrivée est le moment où votre collaborateur se fait une idée de la mission. Un chauffeur qui l'attend, un trajet calme, une arrivée devant un logement dont les clés sont prêtes : la mission commence bien.</p><p>Nous prévoyons aussi l'inverse : le retour vers l'aéroport ou la gare en fin de mission, avec l'état des lieux de sortie organisé le même jour si nécessaire. Et pour les collaborateurs qui rentrent chez eux le week-end, nous pouvons mettre en place des transferts récurrents à jour et heure fixes.</p>"},
        ]},
        {"type": "prose", "heading": "Aéroports et gares : ce qu'il faut savoir", "html": "<p>Roissy-Charles-de-Gaulle est à une quarantaine de kilomètres au nord-est de Paris : comptez de quarante-cinq minutes à plus d'une heure en voiture selon le trafic, et environ trente-cinq minutes en RER B jusqu'au centre. Orly, au sud, est plus proche, mais le trajet dépend beaucoup de la destination finale et de l'heure. Beauvais, utilisé par certaines compagnies à bas coût, est à plus d'une heure. Les taxis parisiens appliquent des tarifs forfaitaires réglementés depuis les aéroports, ce qui évite les mauvaises surprises, mais l'attente peut être longue aux heures de pointe et personne n'attend votre collaborateur à la sortie.</p><p>Pour les arrivées en train, les gares du Nord, de l'Est, de Lyon et Montparnasse sont toutes au cœur de Paris et bien reliées au métro. Un transfert avec chauffeur reste utile pour les personnes chargées de bagages, les arrivées tardives et les logements en dehors de Paris. Nous choisissons avec vous la solution la plus sensée pour chaque arrivée, et nous la notons dans le devis.</p>"},
        {"type": "twocol", "heading": "Ce que nous prenons en compte", "aside": "<p class=\"muted\">Paris se traverse bien en transports en commun, à condition d'habiter au bon endroit. Le reste de l'Île-de-France demande souvent un véhicule.</p>",
         "html": """<dl class="reasons">
<dt>Les horaires réels</dt><dd>Un chantier qui commence à 7 h, un consultant qui finit à 21 h, une équipe en 3×8 : les solutions ne sont pas les mêmes.</dd>
<dt>L'accès au site</dt><dd>Zones d'activité, plateformes logistiques, chantiers en périphérie : nous vérifions comment on y arrive vraiment, et à quelle heure passe le dernier train.</dd>
<dt>Le nombre de personnes</dt><dd>Un chauffeur pour une personne, une navette pour douze : le coût par personne change beaucoup, et nous le calculons pour vous.</dd>
<dt>Les imprévus</dt><dd>Grèves, travaux, vol retardé : nous suivons l'arrivée de votre collaborateur et nous ajustons le transfert si son avion a du retard.</dd>
<dt>Le budget</dt><dd>Passe Navigo, VTC, chauffeur privé, navette : nous proposons plusieurs niveaux et vous choisissez.</dd>
</dl>"""},
        {"type": "steps", "heading": "Comment ça se passe", "items": [
            {"title": "Vous nous communiquez les vols et les horaires", "text": "Numéro de vol ou de train, heure d'arrivée, nombre de personnes et de bagages, adresse du site de mission."},
            {"title": "Nous organisons les trajets", "text": "Transfert d'arrivée, solution quotidienne, déplacements d'équipe si besoin : tout figure dans le devis, avec le logement."},
            {"title": "Vos collaborateurs reçoivent les informations", "text": "Nom du chauffeur, point de rendez-vous, titres de transport, plan d'accès au site : par email et par message avant le départ."},
            {"title": "Nous restons joignables", "text": "Pendant tout le séjour, pour un changement d'horaire, une course supplémentaire ou un retour anticipé."},
        ]},
        {"type": "faq", "heading": "Questions sur les transports", "items": [
            {"q": "Pouvez-vous organiser uniquement les transferts, sans le logement ?", "a": "<p>Oui, si vos collaborateurs sont déjà logés. Mais l'intérêt de nous confier les deux est réel : nous choisissons le logement en fonction des trajets.</p>"},
            {"q": "Que se passe-t-il si le vol est retardé ?", "a": "<p>Nous suivons les arrivées. Le chauffeur est prévenu et attend votre collaborateur, sans frais supplémentaires dans la limite indiquée au devis.</p>"},
            {"q": "Proposez-vous des véhicules de location ?", "a": "<p>Pour les équipes qui ont besoin d'être autonomes sur un chantier, nous pouvons organiser un véhicule utilitaire ou une voiture de location, livrée au logement. Parlez-nous-en au moment du devis.</p>"},
            {"q": "Les trajets quotidiens sont-ils facturés à l'entreprise ?", "a": "<p>Oui, comme le reste : tout passe par le devis et la facture de votre entreprise. Vos collaborateurs n'avancent rien et vous n'avez pas de notes de frais à traiter.</p>"},
        ]},
    ],
},
# ───────────────────────────── BIEN-ÊTRE
{
    "key": "wellbeing", "slug": "services-bien-etre", "alt": "wellbeing-services", "nav": "Bien-être", "priority": "high", "image": "banner-bien-etre.jpg",
    "title": "Services bien-être pour salariés en mission à Paris | Eden Corporate Mobility",
    "desc": "Accueil, conciergerie, activités et accompagnement des familles pour vos collaborateurs en mission à Paris. Une équipe bien installée travaille mieux.",
    "h1": "Le bien-être de vos collaborateurs, pris en charge sur place",
    "lead": "Loin de chez soi, ce sont les petites choses qui pèsent : un frigo vide le premier soir, un pressing introuvable, un dimanche seul dans une ville qu'on ne connaît pas. Nous nous en occupons, pour que vos collaborateurs se consacrent à leur mission et en gardent un bon souvenir.",
    "sections": [
        {"type": "prose", "heading": "Le bien-être en déplacement est un sujet RH, pas un luxe", "html": "<p>Un collaborateur en mission longue cumule les facteurs de fatigue : un logement qui n'est pas le sien, des repas pris sur le pouce, pas de sport, peu de liens sociaux, une famille restée au pays. Les conséquences se mesurent : baisse de concentration, arrêts maladie, refus de la prochaine mission, parfois démission au retour. Pour les équipes de chantier, s'ajoutent les risques liés au manque de repos.</p><p>Les services bien-être répondent à ces situations concrètes. Ce ne sont pas des gadgets : c'est ce qui permet à une personne de bien vivre plusieurs semaines ou plusieurs mois loin de chez elle, et à votre entreprise de garder ses talents. Vous choisissez les services utiles à chaque mission, nous les organisons et nous les facturons sur le même devis que le logement.</p>"},
        {"type": "features", "heading": "Des services à la carte ou en programme complet", "items": [
            {"img": "bienetre-accueil.jpg", "title": "Accueil et installation", "text": "Frigo rempli à l'arrivée, kit d'accueil, présentation du logement et du quartier, aide aux démarches du quotidien (carte de transport, médecin, pharmacie, salle de sport). Votre collaborateur se sent attendu dès le premier soir."},
            {"img": "bienetre-conciergerie.jpg", "title": "Conciergerie pendant le séjour", "text": "Ménage, pressing, courses, réservations de restaurants, livraisons, petits dépannages, colis : un numéro à appeler pour tout ce qui n'est pas la mission. En français et en anglais."},
            {"img": "bienetre-sport.jpg", "title": "Sport et activités", "text": "Abonnement à une salle de sport près du logement, piscine, cours collectifs, découverte de Paris, sorties d'équipe : de quoi garder l'équilibre et la motivation sur les missions longues."},
            {"img": "bienetre-famille.jpg", "title": "Accompagnement des familles", "text": "Pour les expatriations et les mutations : recherche d'école ou de crèche, garde d'enfants, installation du conjoint, rendez-vous administratifs. Une famille bien installée, c'est un collaborateur serein."},
        ]},
        {"type": "media", "items": [
            {"img": "service-bien-etre.jpg", "heading": "Le premier soir", "html": "<p>C'est le moment le plus sensible d'une mission. Votre collaborateur arrive fatigué, souvent tard, dans une ville qu'il ne connaît pas. Nous faisons en sorte qu'il trouve un logement propre et chauffé, un frigo avec de quoi dîner et prendre son petit-déjeuner, le wifi qui fonctionne, et une personne à appeler s'il a une question.</p><p>Le lendemain, nous lui présentons le quartier si vous le souhaitez : où faire ses courses, où prendre le métro, où courir le matin. Une heure qui change tout le reste du séjour.</p>"},
            {"img": "bienetre-programme.jpg", "heading": "Un programme construit avec vous", "html": "<p>Chaque entreprise et chaque collaborateur sont différents. Anna, responsable des services premium, construit le programme avec vous : quelques services à la carte pour une mission de trois semaines, un accompagnement complet pour une expatriation de deux ans avec famille.</p><p>Vous décidez ce qui est inclus, nous nous chargeons du reste, et vous recevez un seul devis. En cours de mission, votre collaborateur peut demander des services supplémentaires ; ils vous sont soumis pour validation avant d'être engagés.</p>"},
        ]},
        {"type": "prose", "heading": "Trois exemples de programmes", "html": "<p><strong>Mission courte de trois semaines, un technicien seul.</strong> Frigo rempli à l'arrivée, présentation du quartier le premier matin, abonnement à la laverie et à une salle de sport près du logement, un numéro pour les imprévus. Peu de choses, mais celles qui comptent quand on ne connaît pas la ville.</p><p><strong>Mission longue de six mois, une consultante du lundi au jeudi.</strong> Accueil et installation, ménage hebdomadaire, pressing, réservations de restaurants pour ses rendez-vous clients, abonnement sportif, et un transfert récurrent vers la gare le jeudi soir pour rentrer chez elle.</p><p><strong>Expatriation de deux ans, un cadre avec sa famille.</strong> Logement temporaire puis appartement familial, recherche d'école et de crèche, accompagnement du conjoint dans ses démarches, aide aux inscriptions administratives, découverte de Paris en famille le premier week-end, conciergerie pendant toute la durée du contrat. Un programme construit avec le service RH du siège, en anglais, et exécuté sur place, en français.</p>"},
        {"type": "twocol", "heading": "Ce que ça change pour vous", "aside": "<p class=\"muted\">Un collaborateur bien installé dort mieux, travaille mieux et accepte plus volontiers la prochaine mission.</p>",
         "html": """<dl class="reasons">
<dt>Des missions qui se passent bien</dt><dd>Moins d'appels au service RH, moins de problèmes logistiques remontés par vos équipes, moins de retards.</dd>
<dt>Des talents que vous gardez</dt><dd>L'accueil réservé à un collaborateur en déplacement pèse dans sa fidélité, surtout s'il se déplace souvent.</dd>
<dt>Une image d'employeur</dt><dd>Vos collaborateurs racontent leur mission. Un bon accueil à Paris devient un argument de recrutement.</dd>
<dt>Un seul interlocuteur</dt><dd>Logement, transports et services sont gérés par la même équipe et facturés ensemble.</dd>
</dl>"""},
        {"type": "faq", "heading": "Questions sur les services bien-être", "items": [
            {"q": "Les services sont-ils obligatoires avec le logement ?", "a": "<p>Non. Vous pouvez nous confier le logement seul. Les services sont proposés à la carte, et vous choisissez ce qui est utile pour chaque mission.</p>"},
            {"q": "Pouvez-vous intervenir pour des équipes de chantier ?", "a": "<p>Oui : courses d'arrivée, ménage, laverie, abonnement sportif, organisation des repas. Des équipes reposées et bien nourries sont des équipes qui tiennent la durée d'un chantier.</p>"},
            {"q": "Comment sont facturés les services ?", "a": "<p>Sur le même devis que le logement, avec un détail par service. Les demandes supplémentaires en cours de séjour sont soumises à votre validation avant d'être engagées.</p>"},
            {"q": "Parlez-vous d'autres langues que le français et l'anglais ?", "a": "<p>Nous travaillons en français et en anglais. Pour d'autres langues, nous nous appuyons sur des partenaires selon les besoins : parlez-nous-en au moment du devis.</p>"},
        ]},
    ],
},
]
