# -*- coding: utf-8 -*-
"""Manifeste des images du site. Chaque entrée = un emplacement d'image.
file : nom du fichier attendu dans assets/img/ (remplacer le placeholder par la vraie image, même nom)
size : (largeur, hauteur) recommandées ; pal : palette du placeholder ; alt : textes alternatifs FR/EN ; prompt : prompt de génération (EN).
"""
STYLE = ("Editorial lifestyle photograph, natural daylight, realistic, 35 mm lens, shallow depth of field, calm premium mood, "
         "muted neutral tones with soft green and warm brass accents, Parisian context (Haussmann facades, zinc roofs, tall windows, herringbone parquet), "
         "no text, no logos, no brand names, no watermark, not oversaturated, not a luxury cliché")
PEOPLE = "diverse professionals aged 25–55, candid, not looking at the camera"

IMAGES = [
    # ── Hero (accueil), diaporama 16:10
    {"file": "hero-1.jpg", "size": (1600, 1000), "pal": "dark", "use": "Accueil — diapositive 1 (logement)",
     "alt": {"fr": "Salon lumineux d'un appartement meublé à Paris, vue sur des immeubles haussmanniens", "en": "Bright living room of a furnished apartment in Paris with a view of Haussmann buildings"},
     "prompt": f"Bright living room of a furnished corporate apartment in Paris, tall window with a view of Haussmann facades, sofa, small desk with a laptop, morning light. {STYLE} --ar 16:10"},
    {"file": "hero-2.jpg", "size": (1600, 1000), "pal": "dark", "use": "Accueil — diapositive 2 (transports)",
     "alt": {"fr": "Chauffeur accueillant une voyageuse d'affaires avec sa valise devant un immeuble parisien", "en": "Driver welcoming a business traveller with her suitcase in front of a Paris building"},
     "prompt": f"A driver in a dark suit holding the rear door of a black sedan open for a business traveller with a cabin suitcase, quiet Paris street with Haussmann facades, early morning. {PEOPLE}. {STYLE} --ar 16:10"},
    {"file": "hero-3.jpg", "size": (1600, 1000), "pal": "dark", "use": "Accueil — diapositive 3 (équipes)",
     "alt": {"fr": "Trois collaborateurs avec bagages arrivant devant une résidence en Île-de-France", "en": "Three colleagues with luggage arriving at a residence in the Paris region"},
     "prompt": f"Three colleagues with rolling suitcases and work bags arriving together at the entrance of a modern residence in the Paris suburbs, one holding keys, late afternoon light. {PEOPLE}. {STYLE} --ar 16:10"},
    {"file": "hero-4.jpg", "size": (1600, 1000), "pal": "mid", "use": "Accueil — diapositive 4 (bien-être)",
     "alt": {"fr": "Table de petit-déjeuner dressée avec un panier de bienvenue dans un appartement meublé", "en": "Breakfast table set with a welcome basket in a furnished apartment"},
     "prompt": f"Welcome basket with fresh bread, fruit and a handwritten card on the kitchen table of a furnished Paris apartment, soft window light, Paris rooftops visible through the window. {STYLE} --ar 16:10"},
    # ── Accueil : services 4:3 et segments 3:2
    {"file": "service-logement.jpg", "size": (1200, 900), "pal": "light", "use": "Accueil — bloc Logement",
     "alt": {"fr": "Chambre d'un appartement meublé avec literie de qualité et lumière naturelle", "en": "Bedroom of a furnished apartment with quality bedding and natural light"},
     "prompt": f"Calm bedroom of a furnished apartment in Paris, crisp white bedding, wooden headboard, tall window with linen curtains, a suitcase on a luggage rack. {STYLE} --ar 4:3"},
    {"file": "service-transports.jpg", "size": (1200, 900), "pal": "dark", "use": "Accueil — bloc Transports",
     "alt": {"fr": "Vue depuis la banquette arrière d'une voiture avec chauffeur traversant Paris", "en": "View from the back seat of a chauffeured car driving through Paris"},
     "prompt": f"View from the back seat of a chauffeured car driving along the Seine in Paris, driver's hands on the wheel, soft bokeh city lights at dusk. {STYLE} --ar 4:3"},
    {"file": "service-bien-etre.jpg", "size": (1200, 900), "pal": "mid", "use": "Accueil — bloc Bien-être",
     "alt": {"fr": "Personne en tenue de sport buvant un café sur un balcon parisien le matin", "en": "Person in sportswear drinking coffee on a Paris balcony in the morning"},
     "prompt": f"A person in running clothes holding a coffee on a small Paris balcony at sunrise, zinc rooftops, relaxed. {PEOPLE}. {STYLE} --ar 4:3"},
    {"file": "home-why.jpg", "size": (1200, 900), "pal": "light", "use": "Accueil — Pourquoi nous choisir",
     "alt": {"fr": "Conseillère de l'agence remettant des clés à un collaborateur dans un appartement", "en": "Agency adviser handing keys to an employee inside an apartment"},
     "prompt": f"A friendly relocation adviser handing apartment keys to a newly arrived employee in a bright Paris apartment, both smiling, natural light. {PEOPLE}. {STYLE} --ar 4:3"},
    {"file": "seg-conseil.jpg", "size": (900, 600), "pal": "light", "use": "Segment Cabinets de conseil (vignette + bannière)",
     "alt": {"fr": "Consultant travaillant sur un ordinateur portable près d'une fenêtre d'appartement parisien", "en": "Consultant working on a laptop by the window of a Paris apartment"},
     "prompt": f"A consultant working on a laptop at a small desk by a tall window in a Paris apartment, notebook and coffee, focused, morning light. {PEOPLE}. {STYLE} --ar 3:2"},
    {"file": "seg-btp.jpg", "size": (900, 600), "pal": "dark", "use": "Segment BTP (vignette + bannière)",
     "alt": {"fr": "Équipe de chantier en gilets de sécurité quittant un chantier en Île-de-France en fin de journée", "en": "Construction crew in safety vests leaving a site in the Paris region at the end of the day"},
     "prompt": f"Construction workers in hi-vis vests and helmets walking out of a building site gate at the end of the day, Paris suburb, cranes in the background, golden hour. {PEOPLE}. {STYLE} --ar 3:2"},
    {"file": "seg-ong.jpg", "size": (900, 600), "pal": "mid", "use": "Segment ONG (vignette + bannière)",
     "alt": {"fr": "Petite équipe en réunion autour d'une table avec ordinateurs et documents", "en": "Small team meeting around a table with laptops and documents"},
     "prompt": f"A small international team in a meeting around a wooden table with laptops and printed documents, bright room in Paris, engaged conversation. {PEOPLE}. {STYLE} --ar 3:2"},
    {"file": "seg-pme.jpg", "size": (900, 600), "pal": "light", "use": "Segment PME / ETI (vignette + bannière)",
     "alt": {"fr": "Dirigeante de PME au téléphone dans un bureau, agenda ouvert", "en": "SME manager on the phone in an office with an open diary"},
     "prompt": f"An SME manager on the phone at her desk, open planner and laptop, small modern office, warm daylight, relieved expression. {PEOPLE}. {STYLE} --ar 3:2"},
    {"file": "seg-intl.jpg", "size": (900, 600), "pal": "dark", "use": "Segment Groupes internationaux (vignette + bannière)",
     "alt": {"fr": "Famille avec valises arrivant à l'aéroport de Paris-Charles-de-Gaulle", "en": "Family with suitcases arriving at Paris-Charles de Gaulle airport"},
     "prompt": f"A family with suitcases walking through an airport arrivals hall, looking hopeful, soft daylight through large windows, blurred crowd. {PEOPLE}. {STYLE} --ar 3:2"},
    # ── Page Logement
    {"file": "banner-logement.jpg", "size": (1600, 1000), "pal": "light", "use": "Logement — bannière",
     "alt": {"fr": "Appartement meublé parisien avec parquet, cuisine ouverte et grandes fenêtres", "en": "Furnished Paris apartment with parquet floor, open kitchen and large windows"},
     "prompt": f"Wide view of a furnished Paris apartment: herringbone parquet, open kitchen, dining table, tall windows, plants, tidy and welcoming. {STYLE} --ar 16:10"},
    {"file": "format-appartement.jpg", "size": (1200, 900), "pal": "light", "use": "Logement — Appartement meublé",
     "alt": {"fr": "Salon et coin bureau d'un appartement meublé à Paris", "en": "Living room and work corner of a furnished apartment in Paris"},
     "prompt": f"Living room of a furnished apartment in Paris with a dedicated work corner, desk lamp, bookshelf, tall window. {STYLE} --ar 4:3"},
    {"file": "format-aparthotel.jpg", "size": (1200, 900), "pal": "mid", "use": "Logement — Aparthotel",
     "alt": {"fr": "Studio d'aparthotel avec kitchenette et lit fait", "en": "Aparthotel studio with kitchenette and made bed"},
     "prompt": f"Modern aparthotel studio: made bed, compact kitchenette, folded towels, large window over a Paris street, hotel-clean. {STYLE} --ar 4:3"},
    {"file": "format-hotel.jpg", "size": (1200, 900), "pal": "dark", "use": "Logement — Hôtel",
     "alt": {"fr": "Réception d'un hôtel parisien avec un voyageur d'affaires", "en": "Reception desk of a Paris hotel with a business traveller"},
     "prompt": f"A business traveller checking in at the reception desk of a boutique hotel in Paris, warm lighting, wood and brass details. {PEOPLE}. {STYLE} --ar 4:3"},
    {"file": "logement-quartier.jpg", "size": (1200, 900), "pal": "light", "use": "Logement — Où loger en Île-de-France",
     "alt": {"fr": "Rue parisienne avec station de métro et immeubles haussmanniens", "en": "Paris street with a metro station and Haussmann buildings"},
     "prompt": f"A Paris street corner with a metro entrance, Haussmann buildings, a café terrace, people commuting, morning. {STYLE} --ar 4:3"},
    {"file": "logement-groupe.jpg", "size": (1200, 900), "pal": "mid", "use": "Logement — Groupes et équipes",
     "alt": {"fr": "Façade d'une résidence moderne avec plusieurs appartements en Île-de-France", "en": "Facade of a modern residence with several apartments in the Paris region"},
     "prompt": f"Facade of a modern mid-rise residence with balconies in a green Paris suburb, clear sky, people at the entrance. {STYLE} --ar 4:3"},
    # ── Page Transports
    {"file": "banner-transports.jpg", "size": (1600, 1000), "pal": "dark", "use": "Transports — bannière",
     "alt": {"fr": "Voiture avec chauffeur attendant devant le terminal d'un aéroport parisien", "en": "Chauffeured car waiting outside a Paris airport terminal"},
     "prompt": f"A black sedan waiting at the curb of an airport terminal at dawn, driver standing beside it with a small name sign (blank), glass facade reflections. {PEOPLE}. {STYLE} --ar 16:10"},
    {"file": "transport-aeroport.jpg", "size": (1200, 900), "pal": "dark", "use": "Transports — Transferts aéroport et gare",
     "alt": {"fr": "Voyageur avec valise sortant d'une gare parisienne", "en": "Traveller with a suitcase leaving a Paris railway station"},
     "prompt": f"A traveller with a cabin suitcase walking out of Gare de Lyon-style station hall into daylight, arches and clock, blurred crowd. {PEOPLE}. {STYLE} --ar 4:3"},
    {"file": "transport-quotidien.jpg", "size": (1200, 900), "pal": "light", "use": "Transports — Trajets quotidiens",
     "alt": {"fr": "Quai de RER avec des voyageurs le matin en Île-de-France", "en": "RER platform with commuters in the morning in the Paris region"},
     "prompt": f"Commuters on a bright suburban train platform in the Paris region in the morning, a train arriving, calm and orderly. {PEOPLE}. {STYLE} --ar 4:3"},
    {"file": "transport-equipe.jpg", "size": (1200, 900), "pal": "mid", "use": "Transports — Déplacements d'équipe",
     "alt": {"fr": "Minibus déposant une équipe devant un bâtiment de bureaux", "en": "Minibus dropping off a team in front of an office building"},
     "prompt": f"A small team stepping out of a clean white minivan in front of a glass office building in La Défense-style district, morning. {PEOPLE}. {STYLE} --ar 4:3"},
    {"file": "transport-coordination.jpg", "size": (1200, 900), "pal": "light", "use": "Transports — Coordination avec le logement",
     "alt": {"fr": "Plan de Paris et carte de transport posés sur une table avec un carnet", "en": "Paris map and travel pass on a table with a notebook"},
     "prompt": f"Top-down view of a paper map of Paris, a transit pass, keys and a notebook with a handwritten schedule on a wooden table. {STYLE} --ar 4:3"},
    # ── Page Bien-être
    {"file": "banner-bien-etre.jpg", "size": (1600, 1000), "pal": "mid", "use": "Bien-être — bannière",
     "alt": {"fr": "Collaboratrice détendue lisant sur un canapé dans un appartement lumineux", "en": "Relaxed employee reading on a sofa in a bright apartment"},
     "prompt": f"A person relaxing on a sofa with a book in a bright furnished apartment after work, plants, warm evening light through tall windows. {PEOPLE}. {STYLE} --ar 16:10"},
    {"file": "bienetre-accueil.jpg", "size": (1200, 900), "pal": "light", "use": "Bien-être — Accueil et installation",
     "alt": {"fr": "Réfrigérateur rempli de produits frais dans un appartement prêt pour l'arrivée", "en": "Fridge stocked with fresh food in an apartment ready for arrival"},
     "prompt": f"An open fridge freshly stocked with fruit, vegetables, yoghurt and juice in a clean apartment kitchen, a welcome note on the counter. {STYLE} --ar 4:3"},
    {"file": "bienetre-conciergerie.jpg", "size": (1200, 900), "pal": "mid", "use": "Bien-être — Conciergerie",
     "alt": {"fr": "Concierge remettant un sac de pressing et des courses à la porte d'un appartement", "en": "Concierge handing dry cleaning and groceries at an apartment door"},
     "prompt": f"A concierge handing a garment bag and a grocery tote to a resident at the door of a Paris apartment, hallway with parquet, friendly. {PEOPLE}. {STYLE} --ar 4:3"},
    {"file": "bienetre-sport.jpg", "size": (1200, 900), "pal": "dark", "use": "Bien-être — Sport et activités",
     "alt": {"fr": "Personne courant le long de la Seine tôt le matin", "en": "Person running along the Seine early in the morning"},
     "prompt": f"A runner on the quays of the Seine at sunrise, bridges and Haussmann buildings in soft light, empty path. {PEOPLE}. {STYLE} --ar 4:3"},
    {"file": "bienetre-famille.jpg", "size": (1200, 900), "pal": "light", "use": "Bien-être — Familles",
     "alt": {"fr": "Parent et enfant devant la grille d'une école parisienne", "en": "Parent and child at the gate of a Paris school"},
     "prompt": f"A parent walking a child with a small backpack to the gate of a Paris school in the morning, tree-lined street. {PEOPLE}. {STYLE} --ar 4:3"},
    {"file": "bienetre-programme.jpg", "size": (1200, 900), "pal": "mid", "use": "Bien-être — Programme sur mesure",
     "alt": {"fr": "Responsable des services prenant des notes lors d'un appel avec une cliente", "en": "Services manager taking notes during a call with a client"},
     "prompt": f"A services manager taking notes in a paper planner during a phone call, bright office, plants, calm. {PEOPLE}. {STYLE} --ar 4:3"},
    # ── À propos, Propriétaires
    {"file": "about-team.jpg", "size": (1200, 900), "pal": "light", "use": "À propos — Comment nous travaillons (remplacer par une vraie photo d'équipe)",
     "alt": {"fr": "L'équipe d'Eden Corporate Mobility en réunion dans ses bureaux", "en": "The Eden Corporate Mobility team in a meeting at its office"},
     "prompt": f"REAL TEAM PHOTO RECOMMENDED. Otherwise: three colleagues discussing around a table with apartment plans and a laptop, bright office. {PEOPLE}. {STYLE} --ar 4:3"},
    {"file": "owners-appartement.jpg", "size": (1200, 900), "pal": "light", "use": "Propriétaires — Ce que nous recherchons",
     "alt": {"fr": "Propriétaire ouvrant les volets d'un appartement meublé à Paris", "en": "Owner opening the shutters of a furnished apartment in Paris"},
     "prompt": f"A property owner opening tall wooden shutters in a furnished Paris apartment, light flooding in, parquet floor. {PEOPLE}. {STYLE} --ar 4:3"},
]

ALT = {"fr": {i["file"]: i["alt"]["fr"] for i in IMAGES}, "en": {i["file"]: i["alt"]["en"] for i in IMAGES}}
SIZE = {i["file"]: i["size"] for i in IMAGES}
